/*
 * Copyright (c) 2015 Huawei, Inc. and others. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */
/* Generated By:JavaCC: Do not edit this line. NEMOparserConstants.java */
package org.opendaylight.nemo.user.vnspacemanager.languagestyle.NEMOParse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NEMOparserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COLON = 5;
  /** RegularExpression Id. */
  int COMMA = 6;
  /** RegularExpression Id. */
  int SEMICOLON = 7;
  /** RegularExpression Id. */
  int LPAREN = 8;
  /** RegularExpression Id. */
  int RPAREN = 9;
  /** RegularExpression Id. */
  int LBRACKET = 10;
  /** RegularExpression Id. */
  int RBRACKET = 11;
  /** RegularExpression Id. */
  int AND = 12;
  /** RegularExpression Id. */
  int OR = 13;
  /** RegularExpression Id. */
  int NOT = 14;
  /** RegularExpression Id. */
  int EQUAL = 15;
  /** RegularExpression Id. */
  int GTHAN = 16;
  /** RegularExpression Id. */
  int LTHAN = 17;
  /** RegularExpression Id. */
  int NLTHAN = 18;
  /** RegularExpression Id. */
  int NMTHAN = 19;
  /** RegularExpression Id. */
  int BETWEEN = 20;
  /** RegularExpression Id. */
  int UNDERSCORE = 21;
  /** RegularExpression Id. */
  int JOINER = 22;
  /** RegularExpression Id. */
  int FSLASH = 23;
  /** RegularExpression Id. */
  int DOT = 24;
  /** RegularExpression Id. */
  int CREATE = 25;
  /** RegularExpression Id. */
  int IMPORT = 26;
  /** RegularExpression Id. */
  int UPDATE = 27;
  /** RegularExpression Id. */
  int DELETE = 28;
  /** RegularExpression Id. */
  int NODE = 29;
  /** RegularExpression Id. */
  int TYPE = 30;
  /** RegularExpression Id. */
  int CONTAIN = 31;
  /** RegularExpression Id. */
  int PROPERTY = 32;
  /** RegularExpression Id. */
  int CONNECTION = 33;
  /** RegularExpression Id. */
  int ENDNODES = 34;
  /** RegularExpression Id. */
  int CONNECTIONPOINT = 35;
  /** RegularExpression Id. */
  int FLOW = 36;
  /** RegularExpression Id. */
  int MATCH = 37;
  /** RegularExpression Id. */
  int OPERATION = 38;
  /** RegularExpression Id. */
  int TARGET = 39;
  /** RegularExpression Id. */
  int CONDITION = 40;
  /** RegularExpression Id. */
  int ACTION = 41;
  /** RegularExpression Id. */
  int QUERY = 42;
  /** RegularExpression Id. */
  int FROM = 43;
  /** RegularExpression Id. */
  int VNFD = 44;
  /** RegularExpression Id. */
  int PRIORITY = 45;
  /** RegularExpression Id. */
  int TRANSACTION = 46;
  /** RegularExpression Id. */
  int BEGIN = 47;
  /** RegularExpression Id. */
  int END = 48;
  /** RegularExpression Id. */
  int NODES = 49;
  /** RegularExpression Id. */
  int CONNECTIONS = 50;
  /** RegularExpression Id. */
  int FLOWS = 51;
  /** RegularExpression Id. */
  int OPERATIONS = 52;
  /** RegularExpression Id. */
  int NODEMODEL = 53;
  /** RegularExpression Id. */
  int TEMPLATEINSTANCE = 54;
  /** RegularExpression Id. */
  int TEMPLATEDEFINITION = 55;
  /** RegularExpression Id. */
  int STRING = 56;
  /** RegularExpression Id. */
  int INTEGER = 57;
  /** RegularExpression Id. */
  int RANGE = 58;
  /** RegularExpression Id. */
  int AT = 59;
  /** RegularExpression Id. */
  int HTTP = 60;
  /** RegularExpression Id. */
  int HTTPS = 61;
  /** RegularExpression Id. */
  int FILE = 62;
  /** RegularExpression Id. */
  int UNUMBER = 63;
  /** RegularExpression Id. */
  int ID = 64;
  /** RegularExpression Id. */
  int TEMPID = 65;
  /** RegularExpression Id. */
  int ETHPREF = 66;
  /** RegularExpression Id. */
  int IPV4PREF = 67;
  /** RegularExpression Id. */
  int DATEVAL = 68;
  /** RegularExpression Id. */
  int TIMEVAL = 69;
  /** RegularExpression Id. */
  int FULLTIME = 70;
  /** RegularExpression Id. */
  int ETHADDR = 71;
  /** RegularExpression Id. */
  int IPV4ADDR = 72;
  /** RegularExpression Id. */
  int URI = 73;
  /** RegularExpression Id. */
  int UBYTE = 74;
  /** RegularExpression Id. */
  int HEXDIGIT = 75;
  /** RegularExpression Id. */
  int YEAR = 76;
  /** RegularExpression Id. */
  int SMONDAY = 77;
  /** RegularExpression Id. */
  int LMONDAY = 78;
  /** RegularExpression Id. */
  int FEBDAY = 79;
  /** RegularExpression Id. */
  int HOUR = 80;
  /** RegularExpression Id. */
  int MINUTE = 81;
  /** RegularExpression Id. */
  int SECOND = 82;
  /** RegularExpression Id. */
  int DIGIT = 83;
  /** RegularExpression Id. */
  int LETTER = 84;
  /** RegularExpression Id. */
  int UPLOWLETTER = 85;
  /** RegularExpression Id. */
  int INNERURI = 86;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\":\"",
    "\",\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"*\"",
    "\"_\"",
    "\"-\"",
    "\"/\"",
    "\".\"",
    "\"CREATE\"",
    "\"IMPORT\"",
    "\"UPDATE\"",
    "\"DELETE\"",
    "\"Node\"",
    "\"Type\"",
    "\"Contain\"",
    "\"Property\"",
    "\"Connection\"",
    "\"Endnodes\"",
    "\"ConnectionPoint\"",
    "\"Flow\"",
    "\"Match\"",
    "\"Operation\"",
    "\"Target\"",
    "\"Condition\"",
    "\"Action\"",
    "\"Query\"",
    "\"From\"",
    "\"VNFD\"",
    "\"Priority\"",
    "\"Transaction\"",
    "\"Begin\"",
    "\"End\"",
    "\"nodes\"",
    "\"connections\"",
    "\"flows\"",
    "\"operations\"",
    "\"NodeModel\"",
    "\"TemplateInstance\"",
    "\"TemplateDefinition\"",
    "\"string\"",
    "\"integer\"",
    "\"range\"",
    "\"at\"",
    "\"http\"",
    "\"https\"",
    "\"file\"",
    "<UNUMBER>",
    "<ID>",
    "<TEMPID>",
    "<ETHPREF>",
    "<IPV4PREF>",
    "<DATEVAL>",
    "<TIMEVAL>",
    "<FULLTIME>",
    "<ETHADDR>",
    "<IPV4ADDR>",
    "<URI>",
    "<UBYTE>",
    "<HEXDIGIT>",
    "<YEAR>",
    "<SMONDAY>",
    "<LMONDAY>",
    "<FEBDAY>",
    "<HOUR>",
    "<MINUTE>",
    "<SECOND>",
    "<DIGIT>",
    "<LETTER>",
    "<UPLOWLETTER>",
    "<INNERURI>",
  };

}

