/*
 * Copyright (c) 2015 Huawei, Inc. and others. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */
/* Generated By:JavaCC: Do not edit this line. NEMOparserTokenManager.java */
package org.opendaylight.nemo.user.vnspacemanager.languagestyle.NEMOParse;
import org.opendaylight.nemo.user.vnspacemanager.languagestyle.updateintentlang.UpdateNodeLang;
import org.opendaylight.nemo.user.vnspacemanager.languagestyle.updateintentlang.UpdateConnectionLang;
import org.opendaylight.nemo.user.vnspacemanager.languagestyle.updateintentlang.UpdateFlowLang;
import org.opendaylight.nemo.user.vnspacemanager.languagestyle.updateintentlang.UpdateOperationLang;
import org.opendaylight.nemo.user.vnspacemanager.languagestyle.deleteintentlang.DeleteNodeLang;
import org.opendaylight.nemo.user.vnspacemanager.languagestyle.deleteintentlang.DeleteConnectionLang;
import org.opendaylight.nemo.user.vnspacemanager.languagestyle.deleteintentlang.DeleteFlowLang;
import org.opendaylight.nemo.user.vnspacemanager.languagestyle.deleteintentlang.DeleteOperationLang;
import org.opendaylight.nemo.user.vnspacemanager.languagestyle.deleteintentlang.DeleteTemplateInstanceLang;
import org.opendaylight.nemo.user.vnspacemanager.languagestyle.deleteintentlang.DeleteTemplateDefinitionLang;
import org.opendaylight.nemo.user.vnspacemanager.languagestyle.Query;
import org.opendaylight.nemo.user.vnspacemanager.languagestyle.NEMOConstants;
import org.opendaylight.nemo.user.vnspacemanager.languagestyle.updateintentlang.UpdateTemplateDefinitionLang;
import org.opendaylight.nemo.user.vnspacemanager.languagestyle.deleteintentlang.DeleteConnectionPointLang;
import org.opendaylight.controller.md.sal.binding.api.DataBroker;
import org.opendaylight.nemo.user.tenantmanager.TenantManage;
import org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.nemo.common.rev151010.UserId;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.ArrayList;
import java.io.StringReader;

/** Token Manager. */
public class NEMOparserTokenManager implements NEMOparserConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x8000000000000L) != 0L)
         {
            jjmatchedKind = 64;
            return 12;
         }
         if ((active0 & 0x804000000000000L) != 0L)
         {
            jjmatchedKind = 64;
            return 227;
         }
         if ((active0 & 0x712000000000000L) != 0L)
         {
            jjmatchedKind = 64;
            return 228;
         }
         return -1;
      case 1:
         if ((active0 & 0x800000000000000L) != 0L)
            return 228;
         if ((active0 & 0x71e000000000000L) != 0L)
         {
            jjmatchedKind = 64;
            jjmatchedPos = 1;
            return 228;
         }
         return -1;
      case 2:
         if ((active0 & 0x71e000000000000L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 64;
               jjmatchedPos = 2;
            }
            return 228;
         }
         return -1;
      case 3:
         if ((active0 & 0x71e000000000000L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 64;
               jjmatchedPos = 3;
            }
            return 228;
         }
         return -1;
      case 4:
         if ((active0 & 0x40a000000000000L) != 0L)
            return 228;
         if ((active0 & 0x314000000000000L) != 0L)
         {
            jjmatchedKind = 64;
            jjmatchedPos = 4;
            return 228;
         }
         return -1;
      case 5:
         if ((active0 & 0x100000000000000L) != 0L)
            return 228;
         if ((active0 & 0x214000000000000L) != 0L)
         {
            jjmatchedKind = 64;
            jjmatchedPos = 5;
            return 228;
         }
         return -1;
      case 6:
         if ((active0 & 0x200000000000000L) != 0L)
            return 228;
         if ((active0 & 0x14000000000000L) != 0L)
         {
            jjmatchedKind = 64;
            jjmatchedPos = 6;
            return 228;
         }
         return -1;
      case 7:
         if ((active0 & 0x14000000000000L) != 0L)
         {
            jjmatchedKind = 64;
            jjmatchedPos = 7;
            return 228;
         }
         return -1;
      case 8:
         if ((active0 & 0x14000000000000L) != 0L)
         {
            jjmatchedKind = 64;
            jjmatchedPos = 8;
            return 228;
         }
         return -1;
      case 9:
         if ((active0 & 0x10000000000000L) != 0L)
            return 228;
         if ((active0 & 0x4000000000000L) != 0L)
         {
            if (jjmatchedPos != 9)
            {
               jjmatchedKind = 64;
               jjmatchedPos = 9;
            }
            return 228;
         }
         return -1;
      case 10:
         if ((active0 & 0x4000000000000L) != 0L)
            return 228;
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         return jjStopAtPos(0, 14);
      case 38:
         return jjMoveStringLiteralDfa1_0(0x1000L);
      case 40:
         return jjStopAtPos(0, 8);
      case 41:
         return jjStopAtPos(0, 9);
      case 42:
         return jjStopAtPos(0, 20);
      case 44:
         return jjStopAtPos(0, 6);
      case 58:
         return jjStopAtPos(0, 5);
      case 59:
         return jjStopAtPos(0, 7);
      case 60:
         jjmatchedKind = 17;
         return jjMoveStringLiteralDfa1_0(0x80000L);
      case 61:
         return jjMoveStringLiteralDfa1_0(0x8000L);
      case 62:
         jjmatchedKind = 16;
         return jjMoveStringLiteralDfa1_0(0x40000L);
      case 65:
         return jjMoveStringLiteralDfa1_0(0x20000000000L);
      case 66:
         return jjMoveStringLiteralDfa1_0(0x800000000000L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x10a82000000L);
      case 68:
         return jjMoveStringLiteralDfa1_0(0x10000000L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x1000400000000L);
      case 70:
         return jjMoveStringLiteralDfa1_0(0x81000000000L);
      case 73:
         return jjMoveStringLiteralDfa1_0(0x4000000L);
      case 77:
         return jjMoveStringLiteralDfa1_0(0x2000000000L);
      case 78:
         return jjMoveStringLiteralDfa1_0(0x20000020000000L);
      case 79:
         return jjMoveStringLiteralDfa1_0(0x4000000000L);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x200100000000L);
      case 81:
         return jjMoveStringLiteralDfa1_0(0x40000000000L);
      case 84:
         return jjMoveStringLiteralDfa1_0(0xc0408040000000L);
      case 85:
         return jjMoveStringLiteralDfa1_0(0x8000000L);
      case 86:
         return jjMoveStringLiteralDfa1_0(0x100000000000L);
      case 91:
         return jjStopAtPos(0, 10);
      case 93:
         return jjStopAtPos(0, 11);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x800000000000000L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x4000000000000L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x8000000000000L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x200000000000000L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x2000000000000L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x10000000000000L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x400000000000000L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x100000000000000L);
      case 124:
         return jjMoveStringLiteralDfa1_0(0x2000L);
      default :
         return jjMoveNfa_0(13, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active0 & 0x1000L) != 0L)
            return jjStopAtPos(1, 12);
         break;
      case 61:
         if ((active0 & 0x8000L) != 0L)
            return jjStopAtPos(1, 15);
         else if ((active0 & 0x40000L) != 0L)
            return jjStopAtPos(1, 18);
         else if ((active0 & 0x80000L) != 0L)
            return jjStopAtPos(1, 19);
         break;
      case 69:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000L);
      case 77:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000L);
      case 78:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000000000L);
      case 80:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000L);
      case 82:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000a000000000L);
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000000L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0xc0800000000000L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x8001000000000L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x201000400000000L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x26010aa0000000L);
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0x10004000000000L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x680100000000L);
      case 116:
         if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 59, 228);
         return jjMoveStringLiteralDfa2_0(active0, 0x100000000000000L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000000L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000L);
      case 124:
         if ((active0 & 0x2000L) != 0L)
            return jjStopAtPos(1, 13);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 68:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000L);
      case 69:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000L);
      case 70:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000000L);
      case 76:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000L);
      case 80:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000L);
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000000L);
      case 100:
         if ((active0 & 0x1000000000000L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x22000420000000L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x10044000000000L);
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000000L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000000L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0xc0000000000000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x404010a80000000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x8081100000000L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x100008000000000L);
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x200022000000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa4_0(active0, 0xa000000L);
      case 68:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStopAtPos(3, 44);
         break;
      case 69:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000L);
      case 79:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000000L);
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000000L);
      case 101:
         if ((active0 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 29;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x40000000L) != 0L)
            return jjStopAtPos(3, 30);
         return jjMoveStringLiteralDfa4_0(active0, 0x222000000000000L);
      case 103:
         return jjMoveStringLiteralDfa4_0(active0, 0x400008000000000L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x100820000000000L);
      case 109:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStopAtPos(3, 43);
         break;
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x4400e00000000L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000000000L);
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0xc0000100000000L);
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x10044000000000L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000L);
      case 119:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStopAtPos(3, 36);
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 77:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000000000L);
      case 82:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000L);
      case 84:
         return jjMoveStringLiteralDfa5_0(active0, 0x1a000000L);
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x10004080000000L);
      case 101:
         if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 58, 228);
         return jjMoveStringLiteralDfa5_0(active0, 0x4008b00000000L);
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x200000000000000L);
      case 104:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStopAtPos(4, 37);
         break;
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000000L);
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0xc0000000000000L);
      case 110:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStopAtPos(4, 47);
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000000000L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x20400000000L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x200000000000L);
      case 115:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 49, 228);
         else if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 51, 228);
         return jjMoveStringLiteralDfa5_0(active0, 0x400000000000L);
      case 121:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStopAtPos(4, 42);
         break;
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x2000000L) != 0L)
            return jjStopAtPos(5, 25);
         else if ((active0 & 0x8000000L) != 0L)
            return jjStopAtPos(5, 27);
         else if ((active0 & 0x10000000L) != 0L)
            return jjStopAtPos(5, 28);
         break;
      case 84:
         if ((active0 & 0x4000000L) != 0L)
            return jjStopAtPos(5, 26);
         break;
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0xc0400000000000L);
      case 99:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000a00000000L);
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000000L);
      case 101:
         return jjMoveStringLiteralDfa6_0(active0, 0x200000000000000L);
      case 103:
         if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 56, 228);
         break;
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x200080000000L);
      case 110:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStopAtPos(5, 41);
         break;
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000000000000L);
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000L);
      case 116:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStopAtPos(5, 39);
         return jjMoveStringLiteralDfa6_0(active0, 0x10014000000000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x400000000000L);
      case 100:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000000000L);
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0x400000000L);
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x10014000000000L);
      case 110:
         if ((active0 & 0x80000000L) != 0L)
            return jjStopAtPos(6, 31);
         break;
      case 114:
         if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 57, 228);
         break;
      case 116:
         return jjMoveStringLiteralDfa7_0(active0, 0xc4200b00000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 101:
         return jjMoveStringLiteralDfa8_0(active0, 0xe0000000000000L);
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x4000a00000000L);
      case 111:
         return jjMoveStringLiteralDfa8_0(active0, 0x10014000000000L);
      case 115:
         if ((active0 & 0x400000000L) != 0L)
            return jjStopAtPos(7, 34);
         break;
      case 116:
         return jjMoveStringLiteralDfa8_0(active0, 0x400000000000L);
      case 121:
         if ((active0 & 0x100000000L) != 0L)
            return jjStopAtPos(7, 32);
         else if ((active0 & 0x200000000000L) != 0L)
            return jjStopAtPos(7, 45);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 68:
         return jjMoveStringLiteralDfa9_0(active0, 0x80000000000000L);
      case 73:
         return jjMoveStringLiteralDfa9_0(active0, 0x40000000000000L);
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0x400000000000L);
      case 108:
         if ((active0 & 0x20000000000000L) != 0L)
            return jjStopAtPos(8, 53);
         break;
      case 110:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStopAtPos(8, 38);
         else if ((active0 & 0x10000000000L) != 0L)
            return jjStopAtPos(8, 40);
         return jjMoveStringLiteralDfa9_0(active0, 0x10000000000000L);
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x4000a00000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 101:
         return jjMoveStringLiteralDfa10_0(active0, 0x80000000000000L);
      case 110:
         if ((active0 & 0x200000000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 9;
         }
         return jjMoveStringLiteralDfa10_0(active0, 0x44000800000000L);
      case 111:
         return jjMoveStringLiteralDfa10_0(active0, 0x400000000000L);
      case 115:
         if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 52, 228);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
static private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 80:
         return jjMoveStringLiteralDfa11_0(active0, 0x800000000L);
      case 102:
         return jjMoveStringLiteralDfa11_0(active0, 0x80000000000000L);
      case 110:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStopAtPos(10, 46);
         break;
      case 115:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 50, 228);
         return jjMoveStringLiteralDfa11_0(active0, 0x40000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
static private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 105:
         return jjMoveStringLiteralDfa12_0(active0, 0x80000000000000L);
      case 111:
         return jjMoveStringLiteralDfa12_0(active0, 0x800000000L);
      case 116:
         return jjMoveStringLiteralDfa12_0(active0, 0x40000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
static private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa13_0(active0, 0x40000000000000L);
      case 105:
         return jjMoveStringLiteralDfa13_0(active0, 0x800000000L);
      case 110:
         return jjMoveStringLiteralDfa13_0(active0, 0x80000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
static private int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0);
      return 13;
   }
   switch(curChar)
   {
      case 105:
         return jjMoveStringLiteralDfa14_0(active0, 0x80000000000000L);
      case 110:
         return jjMoveStringLiteralDfa14_0(active0, 0x40000800000000L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0);
}
static private int jjMoveStringLiteralDfa14_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0);
      return 14;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa15_0(active0, 0x40000000000000L);
      case 116:
         if ((active0 & 0x800000000L) != 0L)
            return jjStopAtPos(14, 35);
         return jjMoveStringLiteralDfa15_0(active0, 0x80000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(13, active0);
}
static private int jjMoveStringLiteralDfa15_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(13, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, active0);
      return 15;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x40000000000000L) != 0L)
            return jjStopAtPos(15, 54);
         break;
      case 105:
         return jjMoveStringLiteralDfa16_0(active0, 0x80000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(14, active0);
}
static private int jjMoveStringLiteralDfa16_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(14, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, active0);
      return 16;
   }
   switch(curChar)
   {
      case 111:
         return jjMoveStringLiteralDfa17_0(active0, 0x80000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(15, active0);
}
static private int jjMoveStringLiteralDfa17_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(15, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(16, active0);
      return 17;
   }
   switch(curChar)
   {
      case 110:
         if ((active0 & 0x80000000000000L) != 0L)
            return jjStopAtPos(17, 55);
         break;
      default :
         break;
   }
   return jjStartNfa_0(16, active0);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 227;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 228:
                  if ((0x7ff600000000000L & l) != 0L)
                     jjCheckNAddTwoStates(225, 226);
                  if ((0x3ff200000000000L & l) != 0L)
                     jjCheckNAddTwoStates(223, 224);
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 65)
                        kind = 65;
                     jjCheckNAdd(226);
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 64)
                        kind = 64;
                     jjCheckNAdd(224);
                  }
                  break;
               case 13:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 4);
                  if ((0x3ff000000000000L & l) != 0L)
                     jjAddStates(5, 6);
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 63)
                        kind = 63;
                     jjCheckNAddStates(7, 9);
                  }
                  else if (curChar == 48)
                  {
                     if (kind > 63)
                        kind = 63;
                     jjCheckNAdd(23);
                  }
                  if (curChar == 50)
                     jjAddStates(10, 11);
                  else if (curChar == 49)
                     jjCheckNAddStates(12, 14);
                  if (curChar == 50)
                     jjAddStates(15, 17);
                  break;
               case 12:
                  if ((0x7ff600000000000L & l) != 0L)
                     jjCheckNAddTwoStates(225, 226);
                  if ((0x3ff200000000000L & l) != 0L)
                     jjCheckNAddTwoStates(223, 224);
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 126;
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 104;
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 65)
                        kind = 65;
                     jjCheckNAdd(226);
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 64)
                        kind = 64;
                     jjCheckNAdd(224);
                  }
                  break;
               case 227:
                  if ((0x7ff600000000000L & l) != 0L)
                     jjCheckNAddTwoStates(225, 226);
                  if ((0x3ff200000000000L & l) != 0L)
                     jjCheckNAddTwoStates(223, 224);
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 126;
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 104;
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 65)
                        kind = 65;
                     jjCheckNAdd(226);
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 64)
                        kind = 64;
                     jjCheckNAdd(224);
                  }
                  break;
               case 1:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 2:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 3:
                  if (curChar == 47)
                     jjCheckNAddTwoStates(4, 5);
                  break;
               case 4:
               case 8:
                  if (curChar == 47)
                     jjCheckNAdd(5);
                  break;
               case 6:
                  if ((0x7ff600000000000L & l) != 0L)
                     jjCheckNAddStates(18, 20);
                  break;
               case 7:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(7, 8);
                  break;
               case 9:
                  if ((0x7ff600000000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddTwoStates(9, 10);
                  break;
               case 10:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAdd(10);
                  break;
               case 22:
                  if (curChar != 48)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAdd(23);
                  break;
               case 23:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(24);
                  break;
               case 24:
                  if (curChar == 58)
                     jjCheckNAddStates(21, 23);
                  break;
               case 25:
                  if (curChar == 48)
                     jjCheckNAdd(26);
                  break;
               case 26:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 27:
                  if (curChar == 58)
                     jjCheckNAddStates(24, 26);
                  break;
               case 28:
                  if (curChar == 48)
                     jjCheckNAdd(29);
                  break;
               case 29:
                  if ((0x3ff000000000000L & l) != 0L && kind > 69)
                     kind = 69;
                  break;
               case 30:
                  if ((0x3e000000000000L & l) != 0L)
                     jjCheckNAdd(29);
                  break;
               case 31:
                  if ((0x3e000000000000L & l) != 0L)
                     jjCheckNAdd(26);
                  break;
               case 32:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAddStates(7, 9);
                  break;
               case 33:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAdd(33);
                  break;
               case 34:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(35);
                  break;
               case 35:
                  if (curChar == 46)
                     jjCheckNAddStates(27, 31);
                  break;
               case 36:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(37);
                  break;
               case 37:
                  if (curChar == 46)
                     jjCheckNAddStates(32, 36);
                  break;
               case 38:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(39);
                  break;
               case 39:
                  if (curChar == 46)
                     jjCheckNAddStates(37, 41);
                  break;
               case 40:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAdd(41);
                  break;
               case 41:
                  if (curChar == 47)
                     jjAddStates(42, 44);
                  break;
               case 42:
                  if ((0x3fe000000000000L & l) != 0L && kind > 67)
                     kind = 67;
                  break;
               case 43:
                  if ((0x6000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 44:
                  if ((0x3ff000000000000L & l) != 0L && kind > 67)
                     kind = 67;
                  break;
               case 45:
                  if (curChar == 51)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 46:
                  if ((0x7000000000000L & l) != 0L && kind > 67)
                     kind = 67;
                  break;
               case 47:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAdd(40);
                  break;
               case 48:
                  if (curChar == 49)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 49:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(40);
                  break;
               case 50:
                  if (curChar == 50)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 51:
                  if ((0x1f000000000000L & l) != 0L)
                     jjCheckNAdd(40);
                  break;
               case 52:
                  if (curChar == 53)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 53:
                  if ((0x3f000000000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAdd(41);
                  break;
               case 54:
                  if (curChar == 50)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 55:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAdd(38);
                  break;
               case 56:
                  if (curChar == 49)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 57:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(38);
                  break;
               case 58:
                  if (curChar == 50)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 59:
                  if ((0x1f000000000000L & l) != 0L)
                     jjCheckNAdd(38);
                  break;
               case 60:
                  if (curChar == 53)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 61:
                  if ((0x3f000000000000L & l) != 0L)
                     jjCheckNAdd(39);
                  break;
               case 62:
                  if (curChar == 50)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 63:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAdd(36);
                  break;
               case 64:
                  if (curChar == 49)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 65:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(36);
                  break;
               case 66:
                  if (curChar == 50)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 67:
                  if ((0x1f000000000000L & l) != 0L)
                     jjCheckNAdd(36);
                  break;
               case 68:
                  if (curChar == 53)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 69:
                  if ((0x3f000000000000L & l) != 0L)
                     jjCheckNAdd(37);
                  break;
               case 70:
                  if (curChar == 50)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 71:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(72);
                  break;
               case 72:
                  if (curChar == 46)
                     jjCheckNAddStates(45, 49);
                  break;
               case 73:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(74);
                  break;
               case 74:
                  if (curChar == 46)
                     jjCheckNAddStates(50, 54);
                  break;
               case 75:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(76);
                  break;
               case 76:
                  if (curChar == 46)
                     jjCheckNAddStates(55, 59);
                  break;
               case 77:
                  if ((0x3ff000000000000L & l) != 0L && kind > 72)
                     kind = 72;
                  break;
               case 78:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAdd(77);
                  break;
               case 79:
                  if (curChar == 49)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 80:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(77);
                  break;
               case 81:
                  if (curChar == 50)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 82:
                  if ((0x1f000000000000L & l) != 0L)
                     jjCheckNAdd(77);
                  break;
               case 83:
                  if (curChar == 53)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 84:
                  if ((0x3f000000000000L & l) != 0L && kind > 72)
                     kind = 72;
                  break;
               case 85:
                  if (curChar == 50)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 86:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAdd(75);
                  break;
               case 87:
                  if (curChar == 49)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 88:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(75);
                  break;
               case 89:
                  if (curChar == 50)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 90:
                  if ((0x1f000000000000L & l) != 0L)
                     jjCheckNAdd(75);
                  break;
               case 91:
                  if (curChar == 53)
                     jjstateSet[jjnewStateCnt++] = 92;
                  break;
               case 92:
                  if ((0x3f000000000000L & l) != 0L)
                     jjCheckNAdd(76);
                  break;
               case 93:
                  if (curChar == 50)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 94:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAdd(73);
                  break;
               case 95:
                  if (curChar == 49)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 96:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(73);
                  break;
               case 97:
                  if (curChar == 50)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 98:
                  if ((0x1f000000000000L & l) != 0L)
                     jjCheckNAdd(73);
                  break;
               case 99:
                  if (curChar == 53)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 100:
                  if ((0x3f000000000000L & l) != 0L)
                     jjCheckNAdd(74);
                  break;
               case 101:
                  if (curChar == 50)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 102:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjAddStates(5, 6);
                  break;
               case 103:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 104:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 105:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 106:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 107:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 108;
                  break;
               case 108:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 109:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 110:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 111;
                  break;
               case 111:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 112:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 113;
                  break;
               case 113:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 114;
                  break;
               case 114:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 115:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 116:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 117;
                  break;
               case 117:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 118;
                  break;
               case 118:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 119:
                  if (curChar == 47)
                     jjAddStates(60, 62);
                  break;
               case 120:
                  if ((0x3fe000000000000L & l) != 0L && kind > 66)
                     kind = 66;
                  break;
               case 121:
                  if ((0xe000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 122:
                  if ((0x3ff000000000000L & l) != 0L && kind > 66)
                     kind = 66;
                  break;
               case 123:
                  if (curChar == 52)
                     jjstateSet[jjnewStateCnt++] = 124;
                  break;
               case 124:
                  if ((0x1ff000000000000L & l) != 0L && kind > 66)
                     kind = 66;
                  break;
               case 125:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 126:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 127:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 128;
                  break;
               case 128:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 129:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 130:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 131:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 132;
                  break;
               case 132:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               case 133:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 134;
                  break;
               case 134:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 135;
                  break;
               case 135:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 136:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 137;
                  break;
               case 137:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 138;
                  break;
               case 138:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 139;
                  break;
               case 139:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 140:
                  if ((0x3ff000000000000L & l) != 0L && kind > 71)
                     kind = 71;
                  break;
               case 141:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 4);
                  break;
               case 142:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 143;
                  break;
               case 143:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 144:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 145;
                  break;
               case 145:
                  if (curChar == 45)
                     jjCheckNAddStates(63, 67);
                  break;
               case 146:
                  if ((0x1aa000000000000L & l) != 0L)
                     jjCheckNAdd(147);
                  break;
               case 147:
                  if (curChar == 45)
                     jjCheckNAddStates(68, 71);
                  break;
               case 148:
               case 156:
               case 161:
                  if (curChar == 48)
                     jjCheckNAdd(149);
                  break;
               case 149:
                  if ((0x3fe000000000000L & l) != 0L && kind > 68)
                     kind = 68;
                  break;
               case 150:
               case 157:
               case 162:
                  if ((0x6000000000000L & l) != 0L)
                     jjCheckNAdd(151);
                  break;
               case 151:
                  if ((0x3ff000000000000L & l) != 0L && kind > 68)
                     kind = 68;
                  break;
               case 152:
                  if (curChar == 51)
                     jjstateSet[jjnewStateCnt++] = 153;
                  break;
               case 153:
                  if ((0x3000000000000L & l) != 0L && kind > 68)
                     kind = 68;
                  break;
               case 154:
                  if ((0x250000000000000L & l) != 0L)
                     jjCheckNAdd(155);
                  break;
               case 155:
                  if (curChar == 45)
                     jjCheckNAddStates(72, 75);
                  break;
               case 158:
                  if (curChar == 48 && kind > 68)
                     kind = 68;
                  break;
               case 159:
                  if (curChar == 51)
                     jjstateSet[jjnewStateCnt++] = 158;
                  break;
               case 160:
                  if (curChar == 45)
                     jjCheckNAddStates(76, 78);
                  break;
               case 163:
                  if (curChar == 50)
                     jjstateSet[jjnewStateCnt++] = 160;
                  break;
               case 164:
                  if (curChar == 48)
                     jjCheckNAddStates(79, 81);
                  break;
               case 165:
                  if (curChar == 49)
                     jjAddStates(82, 84);
                  break;
               case 166:
                  if (curChar == 48)
                     jjCheckNAdd(147);
                  break;
               case 167:
                  if (curChar == 50)
                     jjCheckNAdd(147);
                  break;
               case 168:
                  if (curChar == 49)
                     jjCheckNAdd(155);
                  break;
               case 169:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 170;
                  break;
               case 170:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 171;
                  break;
               case 171:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 172;
                  break;
               case 172:
                  if (curChar == 45)
                     jjCheckNAddStates(85, 89);
                  break;
               case 173:
                  if ((0x1aa000000000000L & l) != 0L)
                     jjCheckNAdd(174);
                  break;
               case 174:
                  if (curChar == 45)
                     jjCheckNAddStates(90, 93);
                  break;
               case 175:
               case 197:
               case 202:
                  if (curChar == 48)
                     jjCheckNAdd(176);
                  break;
               case 176:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAdd(177);
                  break;
               case 177:
                  if (curChar == 44)
                     jjCheckNAddStates(94, 97);
                  break;
               case 178:
                  if (curChar == 48)
                     jjCheckNAdd(179);
                  break;
               case 179:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(180);
                  break;
               case 180:
                  if (curChar == 58)
                     jjCheckNAddStates(98, 100);
                  break;
               case 181:
                  if (curChar == 48)
                     jjCheckNAdd(182);
                  break;
               case 182:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 183;
                  break;
               case 183:
                  if (curChar == 58)
                     jjCheckNAddStates(101, 103);
                  break;
               case 184:
                  if (curChar == 48)
                     jjCheckNAdd(185);
                  break;
               case 185:
                  if ((0x3ff000000000000L & l) != 0L && kind > 70)
                     kind = 70;
                  break;
               case 186:
                  if ((0x3e000000000000L & l) != 0L)
                     jjCheckNAdd(185);
                  break;
               case 187:
                  if ((0x3e000000000000L & l) != 0L)
                     jjCheckNAdd(182);
                  break;
               case 188:
                  if (curChar == 49)
                     jjCheckNAdd(179);
                  break;
               case 189:
                  if (curChar == 50)
                     jjstateSet[jjnewStateCnt++] = 190;
                  break;
               case 190:
                  if ((0xf000000000000L & l) != 0L)
                     jjCheckNAdd(180);
                  break;
               case 191:
               case 198:
               case 203:
                  if ((0x6000000000000L & l) != 0L)
                     jjCheckNAdd(192);
                  break;
               case 192:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(177);
                  break;
               case 193:
                  if (curChar == 51)
                     jjstateSet[jjnewStateCnt++] = 194;
                  break;
               case 194:
                  if ((0x3000000000000L & l) != 0L)
                     jjCheckNAdd(177);
                  break;
               case 195:
                  if ((0x250000000000000L & l) != 0L)
                     jjCheckNAdd(196);
                  break;
               case 196:
                  if (curChar == 45)
                     jjCheckNAddStates(104, 107);
                  break;
               case 199:
                  if (curChar == 48)
                     jjCheckNAdd(177);
                  break;
               case 200:
                  if (curChar == 51)
                     jjstateSet[jjnewStateCnt++] = 199;
                  break;
               case 201:
                  if (curChar == 45)
                     jjCheckNAddStates(108, 110);
                  break;
               case 204:
                  if (curChar == 50)
                     jjstateSet[jjnewStateCnt++] = 201;
                  break;
               case 205:
                  if (curChar == 48)
                     jjCheckNAddStates(111, 113);
                  break;
               case 206:
                  if (curChar == 49)
                     jjAddStates(114, 116);
                  break;
               case 207:
                  if (curChar == 48)
                     jjCheckNAdd(174);
                  break;
               case 208:
                  if (curChar == 50)
                     jjCheckNAdd(174);
                  break;
               case 209:
                  if (curChar == 49)
                     jjCheckNAdd(196);
                  break;
               case 210:
                  if (curChar == 49)
                     jjCheckNAddStates(12, 14);
                  break;
               case 211:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(34);
                  break;
               case 212:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(71);
                  break;
               case 213:
                  if (curChar == 50)
                     jjAddStates(15, 17);
                  break;
               case 214:
                  if ((0x1f000000000000L & l) != 0L)
                     jjCheckNAdd(34);
                  break;
               case 215:
                  if ((0xf000000000000L & l) != 0L)
                     jjCheckNAdd(24);
                  break;
               case 216:
                  if ((0x1f000000000000L & l) != 0L)
                     jjCheckNAdd(71);
                  break;
               case 217:
                  if (curChar == 50)
                     jjAddStates(10, 11);
                  break;
               case 218:
                  if (curChar == 53)
                     jjstateSet[jjnewStateCnt++] = 219;
                  break;
               case 219:
                  if ((0x3f000000000000L & l) != 0L)
                     jjCheckNAdd(35);
                  break;
               case 220:
                  if (curChar == 53)
                     jjstateSet[jjnewStateCnt++] = 221;
                  break;
               case 221:
                  if ((0x3f000000000000L & l) != 0L)
                     jjCheckNAdd(72);
                  break;
               case 223:
                  if ((0x3ff200000000000L & l) != 0L)
                     jjCheckNAddTwoStates(223, 224);
                  break;
               case 224:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 64)
                     kind = 64;
                  jjCheckNAdd(224);
                  break;
               case 225:
                  if ((0x7ff600000000000L & l) != 0L)
                     jjCheckNAddTwoStates(225, 226);
                  break;
               case 226:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 65)
                     kind = 65;
                  jjCheckNAdd(226);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 228:
                  if ((0x7fffffe80000000L & l) != 0L)
                     jjCheckNAddTwoStates(225, 226);
                  if ((0x7fffffe80000000L & l) != 0L)
                     jjCheckNAddTwoStates(223, 224);
                  if ((0x7fffffe00000000L & l) != 0L)
                  {
                     if (kind > 65)
                        kind = 65;
                     jjCheckNAdd(226);
                  }
                  if ((0x7fffffe00000000L & l) != 0L)
                  {
                     if (kind > 64)
                        kind = 64;
                     jjCheckNAdd(224);
                  }
                  break;
               case 13:
                  if ((0x7fffffe00000000L & l) != 0L)
                  {
                     if (kind > 64)
                        kind = 64;
                     jjCheckNAddStates(117, 120);
                  }
                  if ((0x7e00000000L & l) != 0L)
                     jjAddStates(5, 6);
                  else if (curChar == 104)
                     jjAddStates(121, 122);
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 12:
                  if ((0x7fffffe80000000L & l) != 0L)
                     jjCheckNAddTwoStates(225, 226);
                  if ((0x7fffffe80000000L & l) != 0L)
                     jjCheckNAddTwoStates(223, 224);
                  if ((0x7fffffe00000000L & l) != 0L)
                  {
                     if (kind > 65)
                        kind = 65;
                     jjCheckNAdd(226);
                  }
                  if ((0x7fffffe00000000L & l) != 0L)
                  {
                     if (kind > 64)
                        kind = 64;
                     jjCheckNAdd(224);
                  }
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 126;
                  else if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 11;
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 227:
                  if ((0x7fffffe80000000L & l) != 0L)
                     jjCheckNAddTwoStates(225, 226);
                  if ((0x7fffffe80000000L & l) != 0L)
                     jjCheckNAddTwoStates(223, 224);
                  if ((0x7fffffe00000000L & l) != 0L)
                  {
                     if (kind > 65)
                        kind = 65;
                     jjCheckNAdd(226);
                  }
                  if ((0x7fffffe00000000L & l) != 0L)
                  {
                     if (kind > 64)
                        kind = 64;
                     jjCheckNAdd(224);
                  }
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 126;
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 0:
                  if (curChar == 101)
                     jjCheckNAdd(1);
                  break;
               case 5:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(123, 127);
                  break;
               case 6:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(18, 20);
                  break;
               case 7:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(7, 8);
                  break;
               case 9:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddTwoStates(9, 10);
                  break;
               case 10:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAdd(10);
                  break;
               case 11:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 14:
                  if (curChar == 104)
                     jjAddStates(121, 122);
                  break;
               case 15:
                  if (curChar == 112)
                     jjCheckNAdd(1);
                  break;
               case 16:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 17:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 18:
                  if (curChar == 115)
                     jjCheckNAdd(1);
                  break;
               case 19:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 20:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 21:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 102:
                  if ((0x7e00000000L & l) != 0L)
                     jjAddStates(5, 6);
                  break;
               case 103:
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 105:
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 106:
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 108:
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 109:
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 111:
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 112:
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 113;
                  break;
               case 114:
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 115:
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 117:
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 118;
                  break;
               case 118:
                  if ((0x7e00000000L & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 125:
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 127:
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 128;
                  break;
               case 128:
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 130:
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 131:
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 132;
                  break;
               case 133:
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 134;
                  break;
               case 134:
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 135;
                  break;
               case 136:
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 137;
                  break;
               case 137:
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 138;
                  break;
               case 139:
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 140:
                  if ((0x7e00000000L & l) != 0L && kind > 71)
                     kind = 71;
                  break;
               case 222:
                  if ((0x7fffffe00000000L & l) == 0L)
                     break;
                  if (kind > 64)
                     kind = 64;
                  jjCheckNAddStates(117, 120);
                  break;
               case 223:
                  if ((0x7fffffe80000000L & l) != 0L)
                     jjCheckNAddTwoStates(223, 224);
                  break;
               case 224:
                  if ((0x7fffffe00000000L & l) == 0L)
                     break;
                  if (kind > 64)
                     kind = 64;
                  jjCheckNAdd(224);
                  break;
               case 225:
                  if ((0x7fffffe80000000L & l) != 0L)
                     jjCheckNAddTwoStates(225, 226);
                  break;
               case 226:
                  if ((0x7fffffe00000000L & l) == 0L)
                     break;
                  if (kind > 65)
                     kind = 65;
                  jjCheckNAdd(226);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 227 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   35, 142, 24, 169, 72, 103, 125, 33, 34, 71, 218, 220, 211, 23, 212, 214, 
   215, 216, 6, 7, 8, 25, 26, 31, 28, 29, 30, 36, 63, 64, 66, 70, 
   38, 55, 56, 58, 62, 40, 47, 48, 50, 54, 42, 43, 45, 73, 94, 95, 
   97, 101, 75, 86, 87, 89, 93, 77, 78, 79, 81, 85, 120, 121, 123, 146, 
   154, 163, 164, 165, 148, 149, 150, 152, 156, 149, 157, 159, 161, 149, 162, 146, 
   154, 163, 166, 167, 168, 173, 195, 204, 205, 206, 175, 176, 191, 193, 178, 179, 
   188, 189, 181, 182, 187, 184, 185, 186, 197, 176, 198, 200, 202, 176, 203, 173, 
   195, 204, 207, 208, 209, 223, 224, 225, 226, 17, 21, 6, 7, 8, 9, 10, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, "\72", "\54", "\73", "\50", "\51", "\133", "\135", 
"\46\46", "\174\174", "\41", "\75\75", "\76", "\74", "\76\75", "\74\75", "\52", null, 
null, null, null, "\103\122\105\101\124\105", "\111\115\120\117\122\124", 
"\125\120\104\101\124\105", "\104\105\114\105\124\105", "\116\157\144\145", "\124\171\160\145", 
"\103\157\156\164\141\151\156", "\120\162\157\160\145\162\164\171", 
"\103\157\156\156\145\143\164\151\157\156", "\105\156\144\156\157\144\145\163", 
"\103\157\156\156\145\143\164\151\157\156\120\157\151\156\164", "\106\154\157\167", "\115\141\164\143\150", 
"\117\160\145\162\141\164\151\157\156", "\124\141\162\147\145\164", "\103\157\156\144\151\164\151\157\156", 
"\101\143\164\151\157\156", "\121\165\145\162\171", "\106\162\157\155", "\126\116\106\104", 
"\120\162\151\157\162\151\164\171", "\124\162\141\156\163\141\143\164\151\157\156", "\102\145\147\151\156", 
"\105\156\144", "\156\157\144\145\163", "\143\157\156\156\145\143\164\151\157\156\163", 
"\146\154\157\167\163", "\157\160\145\162\141\164\151\157\156\163", 
"\116\157\144\145\115\157\144\145\154", "\124\145\155\160\154\141\164\145\111\156\163\164\141\156\143\145", 
"\124\145\155\160\154\141\164\145\104\145\146\151\156\151\164\151\157\156", "\163\164\162\151\156\147", "\151\156\164\145\147\145\162", 
"\162\141\156\147\145", "\141\164", null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x8ffffffffe1fffe1L, 0x3ffL, 
};
static final long[] jjtoSkip = {
   0x1eL, 0x0L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[227];
static private final int[] jjstateSet = new int[454];
static protected char curChar;
/** Constructor. */
public NEMOparserTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public NEMOparserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 227; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
